# Generated by Django 4.2.6 on 2024-08-03 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0002_new_posts"),
    ]

    operations = [
        migrations.CreateModel(
            name="New_post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=200)),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
                ("likes", models.IntegerField(blank=True)),
                (
                    "poster",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="new_posts",
        ),
    ]
