# Generated by Django 4.2.6 on 2024-08-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0003_new_post_delete_new_posts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="new_post",
            name="likes",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
