# Generated by Django 4.2.6 on 2024-08-03 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0004_alter_new_post_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="new_post",
            name="likes",
        ),
        migrations.AlterField(
            model_name="new_post",
            name="posted_at",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="new_post",
            name="poster",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_by_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="new_post",
            name="likes",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
