# Generated by Django 4.2.6 on 2024-08-03 11:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0005_remove_new_post_likes_alter_new_post_posted_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="new_post",
            name="likes",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
