# Generated by Django 4.2.6 on 2024-08-04 07:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0007_follow_user_followers_user_following"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Follow",
        ),
    ]
