# Generated by Django 4.2.6 on 2024-08-04 10:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0015_remove_followers_following_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Follwing",
            new_name="Following",
        ),
    ]
