# Generated by Django 4.2.6 on 2024-08-05 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0016_rename_follwing_following"),
    ]

    operations = [
        migrations.AlterField(
            model_name="new_post",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="likes_on_a_post", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
