# Generated by Django 4.2.6 on 2024-08-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0017_alter_new_post_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="new_post",
            name="likes_count",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
