# Generated by Django 4.2.6 on 2024-07-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_listings_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="listings",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="listings",
            name="url",
            field=models.CharField(blank=True, max_length=6000),
        ),
    ]
