# Generated by Django 4.2.6 on 2024-07-19 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0007_watchlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchlist",
            name="title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auctions.listings",
            ),
        ),
    ]
