# Generated by Django 4.2.6 on 2024-07-19 07:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0008_watchlist_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="watchlist",
            old_name="watchlist",
            new_name="watchlist_owner",
        ),
    ]
