# Generated by Django 4.2.6 on 2024-07-19 07:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0009_rename_watchlist_watchlist_watchlist_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="listings",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="users_watchlist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="watchlist",
        ),
    ]
