# Generated by Django 4.2.6 on 2024-07-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0011_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="bid",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="listings",
            name="starting_bid",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
